### PR TITLE
Drop runtime dependency on ActiveSupport due to minimum ruby requirement

### PR DESCRIPTION
**Pull request by bdunne**
more_core_extensions/core_ext/object/blank.rb was copied from
https://github.com/rails/rails/blob/v5.0.0/activesupport/lib/active_support/core_ext/object/blank.rb

With the release of ActiveSupport v5.0.0 a minimum required_ruby_version
of '>= 2.2.2' was added.  The code for Blank has been copied here so that
we can continue to support ruby versions that don't meet that requirement.

The test was mostly copied as well, but rewritten in rspec syntax.

ActiveSupport has been added as a development dependency for ruby >= 2.2.2
to allow for testing nested hash features with HashWithIndifferentAccess

### CODE REVIEW

**Comment by bdunne** [comment]
@Fryguy Please review.

cc @jrafanie

**Comment by bdunne** [comment]
I'll rework https://github.com/ManageIQ/ovirt/pull/57 after this is merged.

**Comment by bdunne** [comment]
Not planning to make any additional rubocop changes since the majority of that code is copied.

**Comment by jrafanie** [comment]
Nice work @bdunne 👏

**Pull request merged**
