### PR TITLE
Jason (JSON) for everyone!

### PR DESCRIPTION
**Pull request by NickLaMuro**
I blame @agrare for this pull request existing... [[ref](https://gitter.im/ManageIQ/manageiq?at=5ccc65128446a6023ebd7253)]

cc @Fryguy

### CODE REVIEW

**Comment by djberg96** [comment]
My main complaint with this PR is that it wasn't submitted on Friday the 13th.

**Comment by Fryguy** [comment]
I love it, but it's got to go :smile:

**Comment by NickLaMuro** [comment]
@Fryguy 

WTF

**Comment by NickLaMuro** [comment]
very_disappointed

**Pull request closed without merging**
